name: Terraform Plan on Pull Request

on:
  pull_request:
    branches:
      - main

jobs:
  terraform-plan:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Terraform Initialization
      run: terraform init

    - name: Terraform Plan
      run: terraform plan
      env:
        TF_VAR_github_token: ${{ secrets.TF_VAR_GITHUB_PAT }}
