name: Terraform Apply on Merge to Main

on:
  push:
    branches:
      - main

concurrency:
  group: terraform-run

jobs:
  terraform-plan:
    runs-on: ubuntu-latest
    environment: production
    env: 
      TF_VAR_github_token: ${{ secrets.GH_AUTH_TOKEN}}
      TF_VAR_AWS_ACCOUNT_ID_DEVELOPMENT: ${{ secrets.TF_VAR_AWS_ACCOUNT_ID_DEVELOPMENT }}
      TF_VAR_AWS_ACCOUNT_ID_PRODUCTION: ${{ secrets.TF_VAR_AWS_ACCOUNT_ID_PRODUCTION }}
      TF_VAR_AWS_ACCOUNT_ID_GENERAL: ${{ secrets.TF_VAR_AWS_ACCOUNT_ID_GENERAL }}
    defaults:
      run:
        working-directory: ./environments/prod
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        cli_config_credentials_token: ${{ secrets.GITHUBRTERRAGEN_TF_CLOUD_TOKEN }}

    - name: Terraform Initialization
      run: |
        terraform init

    - name: Terraform Validate
      run: |
        terraform validate

    - name: Terraform Plan
      run: |
        terraform plan -var-file="repocitories.tfvars"   


    - name: Terraform Apply
      run: |
        terraform apply -auto-approve -var-file="repocitories.tfvars" 
