name: Terraform Plan on Pull Request

on:
  pull_request:
    branches: [ "main" ]

jobs:
  terraform-plan:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        cli_config_credentials_token: ${{ secrets.GITHUBRTERRAGEN_TF_CLOUD_TOKEN }}

    - name: Terraform Initialization
      run: |
        cd environments/prod
        terraform init

    - name: Terraform Plan
      run: |
        cd environments/prod
        terraform plan
      env:
        TF_VAR_github_token: ${{ env.TF_VAR_github_token }}
